apiVersion: v1
kind: Pod
metadata:
  name: host-pvc-pod
  labels:
    name: host-pvc-pod
spec:
  volumes:
  - name: host-pvc-vol
    persistentVolumeClaim:
      claimName: host-5m-pvc

  containers:
  - name: nginx-pvc-pod
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: host-pvc-vol
        mountPath: /tmp
