apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-10m-pv
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: host-test
  mountOptions:
    - hard
    - nfsvers=4.1
  
  nfs:
    path: /tmp/nfs
    server: 10.211.55.10
