apiVersion: v1
kind: Pod
metadata:
  name: wp-pod
  labels:
    app: wordpress
    role: website

spec:
  containers:
  - image: wordpress:5
    name: wp-pod
    imagePullPolicy: IfNotPresent
    resources:  # 单个容器内需要限制资源用量
      limits:
        memory: "512Mi"
        cpu: "1"
      requests:
        memory: "128Mi"
        cpu: "0.1"
    ports:
    - containerPort: 80
    envFrom:
    - prefix: 'WORDPRESS_DB_'
      configMapRef:
        name: wp-cm